/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

public class Solution {
    public char findTheDifference(String s, String t) {
        if(s == null || t == null) return '\0';
        int[] info = new int[26];
        for(int i=0; i<s.length(); i++) {
            char c = s.charAt(i);
            info[c-'a']++;
        }
        for(int i=0; i<t.length(); i++) {
            char c = t.charAt(i);
            info[c-'a']--;
        }
        char res = '\0';
        for(int i=0; i<26; i++) {
            if(info[i] != 0) {
                res = (char)(i + 'a');
                break;
            }
        }
        return res;
    }
}
